services:
  - type: web
    name: bestie-server
    env: python
    buildCommand: cd bestyy && pip install -r requirements.txt
    startCommand: cd bestyy && gunicorn --bind=0.0.0.0:8000 bestyy.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: WEB_CONCURRENCY
        value: 4
      - key: PORT
        value: 8000
      - key: DJANGO_SETTINGS_MODULE
        value: bestyy.settings
      - key: PYTHONPATH
        value: bestyy