services:
  - type: web
    name: bestie-server
    env: python
    buildCommand: pip install -r bestyy/requirements.txt
    startCommand: cd bestyy && python manage.py runserver 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: WEB_CONCURRENCY
        value: 4
      - key: PORT
        value: 8000
      - key: DJANGO_SETTINGS_MODULE
        value: bestyy.settings
      - key: PYTHONPATH
        value: .