services:
  - type: web
    name: bestyy
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd bestyy && gunicorn bestyy.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: WEB_CONCURRENCY
        value: 4
