services:
  - type: web
    name: bestyy-backend
    env: python
    plan: free
    runtime: python-3.11.9
    buildCommand: ./bestyy/build.sh
    startCommand: daphne -b 0.0.0.0 -p $PORT bestyy.config.asgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: bestyy.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: *.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: bestyy-db
          property: connectionString
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: https://bestyy-web.vercel.app,https://bestie-server.onrender.com,https://your-frontend-domain.com,https://your-admin-domain.com

databases:
  - name: bestyy-db
    plan: free
    databaseName: bestyy
    user: bestyy_user
