services:
  - type: web
    name: bestyy
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p /opt/render/project/src
      cp -r bestyy/* /opt/render/project/src/
      cd /opt/render/project/src
    startCommand: cd /opt/render/project/src && gunicorn bestyy.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: WEB_CONCURRENCY
        value: 4
      - key: PORT
        value: 8000
      - key: DJANGO_SETTINGS_MODULE
        value: bestyy.settings
      - key: PYTHONPATH
        value: .
