# Generated by Django 5.2 on 2025-12-08 14:24

import django.core.validators
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('shipping_address', models.TextField()),
                ('delivery_address', models.TextField(default='')),
                ('billing_address', models.TextField(blank=True, null=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_confirmed', models.BooleanField(default=False)),
                ('payment_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_otp', models.CharField(blank=True, help_text='Format: DL-XXXXXX', max_length=20, null=True)),
                ('delivery_otp_verified', models.BooleanField(default=False, help_text='True when customer confirms delivery')),
                ('pickup_code', models.CharField(blank=True, help_text='Format: PK-XXXXXX', max_length=20, null=True)),
                ('pickup_code_verified', models.BooleanField(default=False, help_text='True when courier picks up order')),
                ('delivery_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('delivery_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('vendor_paid', models.BooleanField(default=False)),
                ('vendor_paid_at', models.DateTimeField(blank=True, null=True)),
                ('vendor_transfer_code', models.CharField(blank=True, help_text='Paystack transfer code for vendor payment', max_length=50, null=True)),
                ('vendor_transfer_reference', models.CharField(blank=True, help_text='Unique reference for vendor transfer', max_length=50, null=True, unique=True)),
                ('vendor_transfer_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('courier_paid', models.BooleanField(default=False)),
                ('courier_paid_at', models.DateTimeField(blank=True, null=True)),
                ('courier_transfer_code', models.CharField(blank=True, help_text='Paystack transfer code for courier payment', max_length=50, null=True)),
                ('courier_transfer_reference', models.CharField(blank=True, help_text='Unique reference for courier transfer', max_length=50, null=True, unique=True)),
                ('courier_transfer_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('preparing_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('out_for_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('delivery_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('fulfilled', 'Fulfilled'), ('released', 'Released')], default='reserved', max_length=20)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-reserved_at'],
            },
        ),
    ]
