# Generated by Django 5.2 on 2025-12-03 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def check_column_exists(cursor, table_name, column_name):
    """Check if a column exists in a table (works for both PostgreSQL and SQLite)"""
    from django.db import connection
    
    if connection.vendor == 'postgresql':
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name=%s AND column_name=%s;
        """, [table_name, column_name])
        return cursor.fetchone() is not None
    else:  # SQLite
        cursor.execute(f"PRAGMA table_info({table_name});")
        columns = [row[1] for row in cursor.fetchall()]
        return column_name in columns


def add_order_fields_if_not_exist(apps, schema_editor):
    """Add all foreign key fields only if they don't already exist"""
    from django.db import connection
    
    # Define all fields to add with their configurations
    fields_to_add = [
        ('order_order', 'courier_id', 'courier', 
         'user.courierprofile', True, True, 'assigned_orders'),
        ('order_order', 'customer_id', 'customer',
         settings.AUTH_USER_MODEL, False, True, 'customer_orders'),
        ('order_order', 'vendor_id', 'vendor',
         'user.vendorprofile', False, True, 'vendor_orders'),
        ('order_orderitem', 'order_id', 'order',
         'order.order', False, False, 'items'),
        ('order_orderitem', 'product_id', 'product',
         'product.product', False, True, 'order_items'),
        ('order_orderstockreservation', 'order_id', 'order',
         'order.order', False, False, 'stock_reservations'),
        ('order_orderstockreservation', 'product_id', 'product',
         'product.product', False, False, 'stock_reservations'),
    ]
    
    with connection.cursor() as cursor:
        for field_info in fields_to_add:
            table_name = field_info[0]
            column_name = field_info[1]
            field_name = field_info[2]
            to_model = field_info[3]
            blank = field_info[4]
            null = field_info[5]
            related_name = field_info[6]
            
            # Check if column exists
            if not check_column_exists(cursor, table_name, column_name):
                # Get the model
                model_path = table_name.split('_')
                app_label = model_path[0]
                model_name = ''.join(word.capitalize() for word in model_path[1:])
                
                try:
                    Model = apps.get_model(app_label, model_name)
                    
                    # Create the field
                    field = models.ForeignKey(
                        to_model,
                        on_delete=django.db.models.deletion.CASCADE if not null else django.db.models.deletion.SET_NULL,
                        related_name=related_name,
                        blank=blank,
                        null=null
                    )
                    
                    field.set_attributes_from_name(field_name)
                    schema_editor.add_field(Model, field)
                except Exception as e:
                    print(f"Warning: Could not add field {field_name} to {table_name}: {e}")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('product', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Use RunPython to add fields conditionally
        migrations.RunPython(add_order_fields_if_not_exist, migrations.RunPython.noop),
        
        # Keep the rest of the operations (indexes)
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='order_order_order_n_fb1851_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer'], name='order_order_custome_df6711_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['vendor'], name='order_order_vendor__3bad86_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='order_order_status_2f1723_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='order_order_created_ffede0_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='order_order_order_i_854de1_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product'], name='order_order_product_ed1645_idx'),
        ),
        migrations.AddIndex(
            model_name='orderstockreservation',
            index=models.Index(fields=['order'], name='order_order_order_i_db6f81_idx'),
        ),
        migrations.AddIndex(
            model_name='orderstockreservation',
            index=models.Index(fields=['product', 'status'], name='order_order_product_35e105_idx'),
        ),
        migrations.AddIndex(
            model_name='orderstockreservation',
            index=models.Index(fields=['status'], name='order_order_status_5b705d_idx'),
        ),
    ]
