# Generated by Django 5.2 on 2025-11-20 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_delivery_distance_km_order_delivery_fee'),
        ('product', '0003_product_image_product_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('fulfilled', 'Fulfilled'), ('released', 'Released')], default='reserved', max_length=20)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservations', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservations', to='product.product')),
            ],
            options={
                'ordering': ['-reserved_at'],
                'indexes': [models.Index(fields=['order'], name='order_order_order_i_db6f81_idx'), models.Index(fields=['product', 'status'], name='order_order_product_35e105_idx'), models.Index(fields=['status'], name='order_order_status_5b705d_idx')],
            },
        ),
    ]
