# Generated by Django 5.2.4 on 2025-11-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderstockreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='courier_transfer_code',
            field=models.CharField(blank=True, help_text='Paystack transfer code for courier payment', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='courier_transfer_reference',
            field=models.CharField(blank=True, help_text='Unique reference for courier transfer', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='courier_transfer_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor_transfer_code',
            field=models.CharField(blank=True, help_text='Paystack transfer code for vendor payment', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor_transfer_reference',
            field=models.CharField(blank=True, help_text='Unique reference for vendor transfer', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor_transfer_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20),
        ),
    ]
