# Generated by Django 5.2.4 on 2025-11-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_courier_paid_at_order_courier_transfer_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_otp_verified',
            field=models.BooleanField(default=False, help_text='True when customer confirms delivery'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_code_verified',
            field=models.BooleanField(default=False, help_text='True when courier picks up order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_otp',
            field=models.CharField(blank=True, help_text='Format: DL-XXXXXX', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_code',
            field=models.CharField(blank=True, help_text='Format: PK-XXXXXX', max_length=20, null=True),
        ),
    ]
