# Generated by Django 5.2.4 on 2025-09-12 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_ai', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aiprocessinglog',
            new_name='ai_processi_status_623362_idx',
            old_name='ai_process_status_8b2b5a_idx',
        ),
        migrations.RenameIndex(
            model_name='aiprocessinglog',
            new_name='ai_processi_created_5c980d_idx',
            old_name='ai_process_created_8b2b5a_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappmessage',
            new_name='whatsapp_me_convers_28bd23_idx',
            old_name='whatsapp_me_convers_8b2b5a_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappmessage',
            new_name='whatsapp_me_message_71b23b_idx',
            old_name='whatsapp_me_message_8b2b5a_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappmessage',
            new_name='whatsapp_me_is_ai_p_342094_idx',
            old_name='whatsapp_me_is_ai_p_8b2b5a_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappwebhooklog',
            new_name='whatsapp_we_event_t_98c9f1_idx',
            old_name='whatsapp_we_event_t_8b2b5a_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappwebhooklog',
            new_name='whatsapp_we_is_proc_c8ce32_idx',
            old_name='whatsapp_we_is_proc_8b2b5a_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappwebhooklog',
            new_name='whatsapp_we_created_eed77d_idx',
            old_name='whatsapp_we_created_8b2b5a_idx',
        ),
    ]
