# Generated by Django 5.2 on 2025-10-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_ai', '0002_rename_ai_process_status_8b2b5a_idx_ai_processi_status_623362_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airesponsetemplate',
            name='category',
            field=models.CharField(choices=[('greeting', 'Greeting'), ('new_user_greeting', 'New User Greeting'), ('returning_user_greeting', 'Returning User Greeting'), ('order_inquiry', 'Order Inquiry'), ('menu_request', 'Menu Request'), ('delivery_status', 'Delivery Status'), ('payment_help', 'Payment Help'), ('complaint', 'Complaint'), ('general_info', 'General Information'), ('fallback', 'Fallback Response')], max_length=50),
        ),
    ]
