# Generated by Django 5.2 on 2025-10-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_ai', '0003_alter_airesponsetemplate_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airesponsetemplate',
            name='category',
            field=models.CharField(choices=[('greeting', 'Greeting'), ('new_user_greeting', 'New User Greeting'), ('returning_user_greeting', 'Returning User Greeting'), ('food_recommendation', 'Food Recommendation'), ('specific_food_request', 'Specific Food Request'), ('order_inquiry', 'Order Inquiry'), ('menu_request', 'Menu Request'), ('delivery_status', 'Delivery Status'), ('payment_help', 'Payment Help'), ('complaint', 'Complaint'), ('general_info', 'General Information'), ('fallback', 'Fallback Response')], max_length=50),
        ),
    ]
