# Generated by Django 5.2 on 2025-10-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_ai', '0004_alter_airesponsetemplate_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconversation',
            name='onboarding_state',
            field=models.CharField(blank=True, help_text='Current onboarding state (FSM)', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='whatsappconversation',
            name='pending_email',
            field=models.CharField(blank=True, help_text='Pending user email during onboarding', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='whatsappconversation',
            name='pending_link_action',
            field=models.CharField(blank=True, help_text='Type of pending account link (e.g. email)', max_length=64, null=True),
        ),
    ]
