# Generated by Django 5.2 on 2025-11-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_ai', '0005_whatsappconversation_onboarding_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconversation',
            name='pending_verification_action',
            field=models.CharField(blank=True, help_text='Pending verification action (e.g. expired_code)', max_length=64, null=True),
        ),
    ]
