# Generated by Django 5.2 on 2025-11-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_ai', '0006_whatsappconversation_pending_verification_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airesponsetemplate',
            name='ai_model',
            field=models.CharField(default='mistralai/mistral-7b-instruct', max_length=100),
        ),
    ]
