# Generated by Django 5.2 on 2025-11-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_ai', '0007_alter_airesponsetemplate_ai_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconversation',
            name='awaiting_address',
            field=models.BooleanField(default=False, help_text="Whether we're currently awaiting a delivery address from the user"),
        ),
    ]
