# Generated by Django 5.2 on 2025-11-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_ai', '0008_whatsappconversation_awaiting_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconversation',
            name='context_data',
            field=models.JSONField(blank=True, default=dict, help_text='Additional context data for order tracking, etc.'),
        ),
    ]
