# Generated by Django 5.2 on 2025-12-03 08:58

import django.db.models.deletion
from django.db import migrations, models


def add_vendor_field_if_not_exists(apps, schema_editor):
    """
    Add vendor field only if it doesn't already exist.
    This handles production databases where the column may already exist.
    """
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Check if vendor_id column exists (works for both PostgreSQL and SQLite)
        if connection.vendor == 'postgresql':
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name='product_product' AND column_name='vendor_id';
            """)
        else:  # SQLite
            cursor.execute("PRAGMA table_info(product_product);")
            columns = [row[1] for row in cursor.fetchall()]
            exists = 'vendor_id' in columns
            if not exists:
                # For SQLite, we need to use Django's schema editor
                from django.db import models
                Product = apps.get_model('product', 'Product')
                field = models.ForeignKey(
                    'user.VendorProfile',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='products'
                )
                field.set_attributes_from_name('vendor')
                schema_editor.add_field(Product, field)
            return
        
        exists = cursor.fetchone()
        
        if not exists:
            # Column doesn't exist in PostgreSQL, add it
            Product = apps.get_model('product', 'Product')
            field = models.ForeignKey(
                'user.VendorProfile',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='products'
            )
            field.set_attributes_from_name('vendor')
            schema_editor.add_field(Product, field)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_vendor_field_if_not_exists, migrations.RunPython.noop),
    ]
