# Generated by Django 5.2 on 2025-11-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, help_text='Cloudinary image URL', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.URLField(blank=True, help_text='Cloudinary video URL', null=True),
        ),
    ]
