# Generated by Django 5.2 on 2025-12-08 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0002_initial'),
        ('product', '0002_initial'),
        ('user', '0001_initial'),
        ('whatsapp_ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportescalation',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='whatsapp_ai.whatsappconversation'),
        ),
        migrations.AddField(
            model_name='supportescalation',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_escalations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this setting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfer',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='order.order'),
        ),
        migrations.AddField(
            model_name='transferrecipient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_recipients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfer',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='user.transferrecipient'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrecommendationhistory',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favorite',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='user.vendorprofile'),
        ),
        migrations.AddField(
            model_name='cart',
            name='vendor',
            field=models.ForeignKey(help_text='Vendor this cart is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='user.vendorprofile'),
        ),
        migrations.AddField(
            model_name='websitecartitem',
            name='anonymous_cart',
            field=models.ForeignKey(blank=True, help_text='Cart for anonymous users', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='user.anonymouscart'),
        ),
        migrations.AddField(
            model_name='websitecartitem',
            name='product',
            field=models.ForeignKey(help_text='Product being added to cart', on_delete=django.db.models.deletion.CASCADE, related_name='website_cart_items', to='product.product'),
        ),
        migrations.AddField(
            model_name='websitecartitem',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User for authenticated cart', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='website_cart_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('email', 'role'), name='unique_email_role'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'menu_item')},
        ),
        migrations.AddIndex(
            model_name='episodicmemory',
            index=models.Index(fields=['user', 'memory_type'], name='ai_episodic_user_id_a3a0b6_idx'),
        ),
        migrations.AddIndex(
            model_name='episodicmemory',
            index=models.Index(fields=['timestamp'], name='ai_episodic_timesta_b86a88_idx'),
        ),
        migrations.AddIndex(
            model_name='episodicmemory',
            index=models.Index(fields=['importance_score'], name='ai_episodic_importa_eac1bd_idx'),
        ),
        migrations.AddIndex(
            model_name='episodicmemory',
            index=models.Index(fields=['session_id'], name='ai_episodic_session_c2b4a1_idx'),
        ),
        migrations.AddIndex(
            model_name='episodicmemory',
            index=models.Index(fields=['conversation_id'], name='ai_episodic_convers_d432ab_idx'),
        ),
        migrations.AddIndex(
            model_name='imageupload',
            index=models.Index(fields=['image_hash', 'image_type', 'is_active'], name='user_imageu_image_h_1fe30b_idx'),
        ),
        migrations.AddIndex(
            model_name='imageupload',
            index=models.Index(fields=['user', 'image_type'], name='user_imageu_user_id_7ac288_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryretrievallog',
            index=models.Index(fields=['user', 'retrieval_type'], name='ai_memory_r_user_id_e0a199_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryretrievallog',
            index=models.Index(fields=['created_at'], name='ai_memory_r_created_61cb38_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryretrievallog',
            index=models.Index(fields=['success'], name='ai_memory_r_success_c1879e_idx'),
        ),
        migrations.AddIndex(
            model_name='periodicmemory',
            index=models.Index(fields=['user', 'pattern_type'], name='ai_periodic_user_id_4e420b_idx'),
        ),
        migrations.AddIndex(
            model_name='periodicmemory',
            index=models.Index(fields=['frequency'], name='ai_periodic_frequen_1ec939_idx'),
        ),
        migrations.AddIndex(
            model_name='periodicmemory',
            index=models.Index(fields=['confidence'], name='ai_periodic_confide_acc91b_idx'),
        ),
        migrations.AddIndex(
            model_name='periodicmemory',
            index=models.Index(fields=['last_observed'], name='ai_periodic_last_ob_186fd8_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationcontext',
            index=models.Index(fields=['user', 'session_id'], name='ai_conversa_user_id_450847_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationcontext',
            index=models.Index(fields=['conversation_id'], name='ai_conversa_convers_4d744d_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationcontext',
            index=models.Index(fields=['last_activity'], name='ai_conversa_last_ac_f172c5_idx'),
        ),
        migrations.AddIndex(
            model_name='systemsettings',
            index=models.Index(fields=['key', 'is_active'], name='user_system_key_db1f02_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'food_item', 'vendor')},
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', 'vendor', 'is_active'], name='user_cart_user_id_7e8404_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['session_key', 'vendor', 'is_active'], name='user_cart_session_f88b66_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['status', 'updated_at'], name='user_cart_status_bbcacd_idx'),
        ),
        migrations.AddConstraint(
            model_name='websitecartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('anonymous_cart__isnull', False)), fields=('anonymous_cart', 'product'), name='unique_anonymous_cart_product'),
        ),
        migrations.AddConstraint(
            model_name='websitecartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'product'), name='unique_user_product'),
        ),
    ]
