# Generated by Django 5.2 on 2025-12-03 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def check_column_exists(cursor, table_name, column_name):
    """Check if a column exists in a table (works for both PostgreSQL and SQLite)"""
    from django.db import connection
    
    if connection.vendor == 'postgresql':
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name=%s AND column_name=%s;
        """, [table_name, column_name])
        return cursor.fetchone() is not None
    else:  # SQLite
        cursor.execute(f"PRAGMA table_info({table_name});")
        columns = [row[1] for row in cursor.fetchall()]
        return column_name in columns


def add_fields_if_not_exist(apps, schema_editor):
    """Add all foreign key fields only if they don't already exist"""
    from django.db import connection
    
    # Define all fields to add with their configurations
    fields_to_add = [
        ('user_supportescalation', 'conversation_id', 'conversation', 
         'whatsapp_ai.whatsappconversation', False, False, 'escalations'),
        ('user_supportescalation', 'resolved_by_id', 'resolved_by',
         settings.AUTH_USER_MODEL, True, True, 'resolved_escalations'),
        ('user_systemsettings', 'updated_by_id', 'updated_by',
         settings.AUTH_USER_MODEL, True, True, 'updated_settings'),
        ('order_transfer', 'order_id', 'order',
         'order.order', True, True, 'transfers'),
        ('user_transferrecipient', 'user_id', 'user',
         settings.AUTH_USER_MODEL, False, False, 'transfer_recipients'),
        ('order_transfer', 'recipient_id', 'recipient',
         'user.transferrecipient', False, False, 'transfers'),
        ('user_userprofile', 'user_id', 'user',
         settings.AUTH_USER_MODEL, False, False, 'profile', True),  # OneToOne
        ('user_userrecommendationhistory', 'user_id', 'user',
         settings.AUTH_USER_MODEL, False, False, 'recommendation_history', True),  # OneToOne
        ('user_vendorprofile', 'user_id', 'user',
         settings.AUTH_USER_MODEL, False, False, 'vendor_profile', True),  # OneToOne
        ('user_favorite', 'vendor_id', 'vendor',
         'user.vendorprofile', True, True, 'favorites'),
        ('user_cart', 'vendor_id', 'vendor',
         'user.vendorprofile', False, False, 'carts'),
        ('user_websitecartitem', 'anonymous_cart_id', 'anonymous_cart',
         'user.anonymouscart', True, True, 'items'),
        ('user_websitecartitem', 'product_id', 'product',
         'product.product', False, False, 'website_cart_items'),
        ('user_websitecartitem', 'user_id', 'user',
         settings.AUTH_USER_MODEL, True, True, 'website_cart_items'),
    ]
    
    with connection.cursor() as cursor:
        for field_info in fields_to_add:
            table_name = field_info[0]
            column_name = field_info[1]
            field_name = field_info[2]
            to_model = field_info[3]
            blank = field_info[4]
            null = field_info[5]
            related_name = field_info[6]
            is_one_to_one = len(field_info) > 7 and field_info[7]
            
            # Check if column exists
            if not check_column_exists(cursor, table_name, column_name):
                # Get the model
                model_path = table_name.split('_')
                app_label = model_path[0]
                model_name = ''.join(word.capitalize() for word in model_path[1:])
                
                try:
                    Model = apps.get_model(app_label, model_name)
                    
                    # Create the field
                    if is_one_to_one:
                        field = models.OneToOneField(
                            to_model,
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name=related_name
                        )
                    else:
                        field = models.ForeignKey(
                            to_model,
                            on_delete=django.db.models.deletion.CASCADE if not null else django.db.models.deletion.SET_NULL,
                            related_name=related_name,
                            blank=blank,
                            null=null
                        )
                    
                    field.set_attributes_from_name(field_name)
                    schema_editor.add_field(Model, field)
                except Exception as e:
                    print(f"Warning: Could not add field {field_name} to {table_name}: {e}")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0002_initial'),
        ('product', '0002_initial'),
        ('user', '0001_initial'),
        ('whatsapp_ai', '0001_initial'),
    ]

    operations = [
        # Use RunPython to add fields conditionally
        migrations.RunPython(add_fields_if_not_exist, migrations.RunPython.noop),
        
        # Keep the rest of the operations (constraints and indexes)
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('email', 'role'), name='unique_email_role'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'menu_item')},
        ),
        migrations.AddIndex(
            model_name='episodicmemory',
            index=models.Index(fields=['user', 'memory_type'], name='ai_episodic_user_id_a3a0b6_idx'),
        ),
        migrations.AddIndex(
            model_name='episodicmemory',
            index=models.Index(fields=['timestamp'], name='ai_episodic_timesta_b86a88_idx'),
        ),
        migrations.AddIndex(
            model_name='episodicmemory',
            index=models.Index(fields=['importance_score'], name='ai_episodic_importa_eac1bd_idx'),
        ),
        migrations.AddIndex(
            model_name='episodicmemory',
            index=models.Index(fields=['session_id'], name='ai_episodic_session_c2b4a1_idx'),
        ),
        migrations.AddIndex(
            model_name='episodicmemory',
            index=models.Index(fields=['conversation_id'], name='ai_episodic_convers_d432ab_idx'),
        ),
        migrations.AddIndex(
            model_name='imageupload',
            index=models.Index(fields=['image_hash', 'image_type', 'is_active'], name='user_imageu_image_h_1fe30b_idx'),
        ),
        migrations.AddIndex(
            model_name='imageupload',
            index=models.Index(fields=['user', 'image_type'], name='user_imageu_user_id_7ac288_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryretrievallog',
            index=models.Index(fields=['user', 'retrieval_type'], name='ai_memory_r_user_id_e0a199_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryretrievallog',
            index=models.Index(fields=['created_at'], name='ai_memory_r_created_61cb38_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryretrievallog',
            index=models.Index(fields=['success'], name='ai_memory_r_success_c1879e_idx'),
        ),
        migrations.AddIndex(
            model_name='periodicmemory',
            index=models.Index(fields=['user', 'pattern_type'], name='ai_periodic_user_id_4e420b_idx'),
        ),
        migrations.AddIndex(
            model_name='periodicmemory',
            index=models.Index(fields=['frequency'], name='ai_periodic_frequen_1ec939_idx'),
        ),
        migrations.AddIndex(
            model_name='periodicmemory',
            index=models.Index(fields=['confidence'], name='ai_periodic_confide_acc91b_idx'),
        ),
        migrations.AddIndex(
            model_name='periodicmemory',
            index=models.Index(fields=['last_observed'], name='ai_periodic_last_ob_186fd8_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationcontext',
            index=models.Index(fields=['user', 'session_id'], name='ai_conversa_user_id_450847_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationcontext',
            index=models.Index(fields=['conversation_id'], name='ai_conversa_convers_4d744d_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationcontext',
            index=models.Index(fields=['last_activity'], name='ai_conversa_last_ac_f172c5_idx'),
        ),
        migrations.AddIndex(
            model_name='systemsettings',
            index=models.Index(fields=['key', 'is_active'], name='user_system_key_db1f02_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'food_item', 'vendor')},
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', 'vendor', 'is_active'], name='user_cart_user_id_7e8404_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['session_key', 'vendor', 'is_active'], name='user_cart_session_f88b66_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['status', 'updated_at'], name='user_cart_status_bbcacd_idx'),
        ),
        migrations.AddConstraint(
            model_name='websitecartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('anonymous_cart__isnull', False)), fields=('anonymous_cart', 'product'), name='unique_anonymous_cart_product'),
        ),
        migrations.AddConstraint(
            model_name='websitecartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'product'), name='unique_user_product'),
        ),
    ]
