# Generated by Django 5.2.4 on 2025-12-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_add_userprofile_user_fk'),
    ]

    operations = [
        # Change VendorProfile logo from ImageField to URLField
        migrations.AlterField(
            model_name='vendorprofile',
            name='logo',
            field=models.URLField(
                blank=True,
                null=True,
                help_text='Vendor logo URL (usually from Cloudinary)'
            ),
        ),
        # Change VendorProfile cover_image from ImageField to URLField
        migrations.AlterField(
            model_name='vendorprofile',
            name='cover_image',
            field=models.URLField(
                blank=True,
                null=True,
                help_text='Vendor cover photo URL (usually from Cloudinary)'
            ),
        ),
        # Also update CourierProfile fields if they exist
        migrations.AlterField(
            model_name='courierprofile',
            name='profile_photo',
            field=models.URLField(
                blank=True,
                null=True,
                help_text='Courier profile photo URL (usually from Cloudinary)'
            ),
        ),
        migrations.AlterField(
            model_name='courierprofile',
            name='id_upload',
            field=models.URLField(
                blank=True,
                null=True,
                help_text='Courier ID document URL (usually from Cloudinary)'
            ),
        ),
        # Update UserProfile profile_picture if it exists
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.URLField(
                blank=True,
                null=True,
                help_text='User profile picture URL (usually from Cloudinary)'
            ),
        ),
    ]
