# Generated by Django 5.2 on 2025-11-08 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='food_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='product.product'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='user.vendorprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'food_item', 'vendor')},
        ),
    ]