# Generated by Django 5.2 on 2025-11-08 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_add_order_foreign_key'),
        ('user', '0003_add_favorite_foreign_keys'),
    ]

    operations = [
    ]
