# Generated by Django 5.2 on 2025-11-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_merge_20251108_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecommendationhistory',
            name='featured_expiry',
            field=models.DateTimeField(blank=True, help_text='When the featured status expires', null=True),
        ),
        migrations.AddField(
            model_name='userrecommendationhistory',
            name='featured_priority',
            field=models.IntegerField(default=0, help_text='Priority order for featured vendors (higher = more prominent)'),
        ),
        migrations.AddField(
            model_name='userrecommendationhistory',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Whether this vendor is currently featured'),
        ),
    ]
