# Generated by Django 5.2.4 on 2025-09-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierprofile',
            name='activation_date',
            field=models.DateTimeField(blank=True, help_text='When the account was last activated', null=True),
        ),
        migrations.AddField(
            model_name='courierprofile',
            name='is_suspended',
            field=models.BooleanField(default=False, help_text='Whether the courier account is currently suspended'),
        ),
        migrations.AddField(
            model_name='courierprofile',
            name='suspension_date',
            field=models.DateTimeField(blank=True, help_text='When the account was suspended', null=True),
        ),
        migrations.AddField(
            model_name='courierprofile',
            name='suspension_duration_days',
            field=models.IntegerField(blank=True, help_text='Duration of suspension in days (null for indefinite)', null=True),
        ),
        migrations.AddField(
            model_name='courierprofile',
            name='suspension_reason',
            field=models.TextField(blank=True, help_text='Reason for account suspension', null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='activation_date',
            field=models.DateTimeField(blank=True, help_text='When the account was last activated', null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='is_suspended',
            field=models.BooleanField(default=False, help_text='Whether the vendor account is currently suspended'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='suspension_date',
            field=models.DateTimeField(blank=True, help_text='When the account was suspended', null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='suspension_duration_days',
            field=models.IntegerField(blank=True, help_text='Duration of suspension in days (null for indefinite)', null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='suspension_reason',
            field=models.TextField(blank=True, help_text='Reason for account suspension', null=True),
        ),
    ]
