# Generated by Django 5.2 on 2025-11-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20251109_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorprofile',
            name='featured_expiry',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='featured_priority',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Vendor cover photo for profile display', null=True, upload_to='vendor_covers/'),
        ),
    ]
