# Generated by Django 5.2 on 2025-11-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_vendorprofile_featured_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierprofile',
            name='last_location_update',
            field=models.DateTimeField(blank=True, help_text='When the location was last updated', null=True),
        ),
        migrations.AddField(
            model_name='courierprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Current latitude of the courier', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='courierprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Current longitude of the courier', max_digits=9, null=True),
        ),
    ]
