# Generated by Django 5.2.4 on 2025-09-12 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_add_suspension_fields'),
    ]

    operations = [
    ]
