# Generated by Django 5.2.4 on 2025-09-12 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0008_auto_20250912_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='customuser_set', related_query_name='customuser', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_set', related_query_name='customuser', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Banner title for admin reference', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Banner description', null=True)),
                ('banner_image', models.ImageField(help_text='Banner image (recommended size: 1180x192)', upload_to='banners/')),
                ('banner_type', models.CharField(choices=[('homepage', 'Homepage Banner'), ('promotional', 'Promotional Banner'), ('seasonal', 'Seasonal Banner'), ('vendor_spotlight', 'Vendor Spotlight')], default='homepage', help_text='Type of banner', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('scheduled', 'Scheduled'), ('expired', 'Expired')], default='active', help_text='Banner status', max_length=20)),
                ('priority', models.IntegerField(default=0, help_text='Display priority (higher number = higher priority)')),
                ('click_url', models.URLField(blank=True, help_text='URL to redirect when banner is clicked', null=True)),
                ('target_audience', models.JSONField(blank=True, default=list, help_text="Target audience (e.g., ['new_users', 'premium_users'])")),
                ('display_start_date', models.DateTimeField(blank=True, help_text='When to start displaying the banner', null=True)),
                ('display_end_date', models.DateTimeField(blank=True, help_text='When to stop displaying the banner', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin user who created the banner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_banners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='user.vendorprofile')),
            ],
            options={
                'verbose_name': 'Shopping Cart',
                'verbose_name_plural': 'Shopping Carts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variants', models.JSONField(default=list, help_text='Selected variants with prices')),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='user.cart')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.menuitem')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Large', 'Extra Cheese'", max_length=100)),
                ('type', models.CharField(choices=[('size', 'Size'), ('extra', 'Extra'), ('addon', 'Add-on'), ('substitute', 'Substitute')], default='size', max_length=20)),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0.0, help_text='Additional price (positive) or discount (negative)', max_digits=10)),
                ('is_required', models.BooleanField(default=False, help_text='Is this variant required?')),
                ('is_available', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='user.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item Variant',
                'verbose_name_plural': 'Menu Item Variants',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variants', models.JSONField(default=list, help_text='Selected variants with prices')),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='user.order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_locations', models.JSONField(blank=True, default=list, help_text='List of preferred city/area names')),
                ('current_city', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_cuisines', models.JSONField(blank=True, default=list, help_text='List of preferred cuisine types')),
                ('dietary_restrictions', models.JSONField(blank=True, default=list, help_text='List of dietary restrictions')),
                ('price_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('prefers_delivery', models.BooleanField(default=True)),
                ('max_delivery_time', models.IntegerField(blank=True, help_text='Maximum acceptable delivery time in minutes', null=True)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_order_date', models.DateTimeField(blank=True, null=True)),
                ('enable_location_based', models.BooleanField(default=True)),
                ('enable_behavioral', models.BooleanField(default=True)),
                ('enable_social', models.BooleanField(default=True, help_text='Recommend based on what others in same location order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorPopularity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('city_orders', models.JSONField(blank=True, default=dict, help_text='Orders count by city')),
                ('city_revenue', models.JSONField(blank=True, default=dict, help_text='Revenue by city')),
                ('orders_last_30_days', models.PositiveIntegerField(default=0)),
                ('orders_last_7_days', models.PositiveIntegerField(default=0)),
                ('recommendation_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='popularity', to='user.vendorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='VendorSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('featured', 'Featured')], default='basic', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('featured_priority', models.IntegerField(default=0, help_text='Higher number = higher priority in recommendations')),
                ('featured_expiry', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='user.vendorprofile')),
            ],
            options={
                'ordering': ['-featured_priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('review_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to='user.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_ratings', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='user.vendorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('vendor', 'user', 'order')},
            },
        ),
    ]
