# Generated by Django 5.2 on 2025-11-10 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_image_product_video'),
        ('user', '0008_courierprofile_last_location_update_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Django session key for anonymous users', max_length=40, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('abandoned', 'Abandoned'), ('converted', 'Converted to Order')], default='active', help_text='Current status of the cart', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, help_text='Total price of all items in cart', max_digits=10)),
                ('item_count', models.PositiveIntegerField(default=0, help_text='Total number of items in cart')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this cart is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who owns the cart (null for anonymous carts)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(help_text='Vendor this cart is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='user.vendorprofile')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Price per unit at time of adding to cart', max_digits=8)),
                ('variants', models.JSONField(blank=True, default=dict, help_text='Selected variants (size, toppings, etc.)')),
                ('special_instructions', models.TextField(blank=True, help_text='Special preparation instructions')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price for this item (base_price * quantity)', max_digits=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='user.cart')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='product.product')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
                'ordering': ['added_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', 'vendor', 'is_active'], name='user_cart_user_id_7e8404_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['session_key', 'vendor', 'is_active'], name='user_cart_session_f88b66_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['status', 'updated_at'], name='user_cart_status_bbcacd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'menu_item')},
        ),
    ]
