# Generated by Django 5.2 on 2025-11-12 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_add_order_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DedicatedVirtualAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paystack_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('paystack_dedicated_account_id', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_slug', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_assigned', models.BooleanField(default=True)),
                ('assignment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dedicated_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dedicated Virtual Account',
                'verbose_name_plural': 'Dedicated Virtual Accounts',
            },
        ),
    ]
