# Generated by Django 5.2.4 on 2025-09-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_courierprofile_area_courierprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_otp',
            field=models.CharField(blank=True, help_text='OTP for delivery confirmation', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_otp_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_otp_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor_otp',
            field=models.CharField(blank=True, help_text='OTP for vendor pickup verification', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor_otp_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor_otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor_otp_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
