# Generated by Django 5.2 on 2025-11-12 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_dedicatedvirtualaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique key for the setting', max_length=100, unique=True)),
                ('value', models.TextField(help_text='Value of the setting (stored as string, cast based on data_type)')),
                ('description', models.TextField(blank=True, help_text='Description of what this setting controls')),
                ('data_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', help_text='Data type for proper casting', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this setting is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this setting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'ordering': ['key'],
                'indexes': [models.Index(fields=['key', 'is_active'], name='user_system_key_db1f02_idx')],
            },
        ),
    ]
