# Generated by Django 5.2.4 on 2025-09-26 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_order_delivery_otp_order_delivery_otp_generated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DedicatedVirtualAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paystack_customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('paystack_dedicated_account_id', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_slug', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_assigned', models.BooleanField(default=False)),
                ('assignment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('subaccount_code', models.CharField(blank=True, max_length=50, null=True)),
                ('split_code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dedicated_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dedicated Virtual Account',
                'verbose_name_plural': 'Dedicated Virtual Accounts',
            },
        ),
        migrations.CreateModel(
            name='TransferRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('vendor', 'Vendor'), ('courier', 'Courier')], max_length=20)),
                ('paystack_recipient_code', models.CharField(max_length=50, unique=True)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=100)),
                ('bank_code', models.CharField(max_length=10)),
                ('bank_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_recipient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transfer Recipient',
                'verbose_name_plural': 'Transfer Recipients',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paystack_reference', models.CharField(max_length=100, unique=True)),
                ('paystack_transfer_code', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='user.order')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='user.transferrecipient')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
                'ordering': ['-initiated_at'],
            },
        ),
    ]
