# Generated by Django 5.2 on 2025-11-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Whether this user has an active featured subscription'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_code',
            field=models.CharField(blank=True, help_text='Paystack subscription code for this user', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], help_text='Current status of user subscription', max_length=20, null=True),
        ),
    ]
