# Generated by Django 5.2.4 on 2025-09-26 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_dedicatedvirtualaccount_transferrecipient_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='dedicatedvirtualaccount',
            name='last_menu_update',
            field=models.DateTimeField(blank=True, help_text='When menu was last updated', null=True),
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_commission_percentage', models.DecimalField(decimal_places=2, default=10.0, help_text='Percentage commission charged on vendor sales (e.g., 10.00 for 10%)', max_digits=5)),
                ('base_delivery_fee', models.DecimalField(decimal_places=2, default=500.0, help_text='Base delivery fee charged to customers', max_digits=10)),
                ('delivery_fee_per_km', models.DecimalField(decimal_places=2, default=150.0, help_text='Additional delivery fee per kilometer', max_digits=10)),
                ('rider_base_fee', models.DecimalField(decimal_places=2, default=1500.0, help_text='Base fee paid to rider for delivery', max_digits=10)),
                ('rider_fee_per_km', models.DecimalField(decimal_places=2, default=150.0, help_text='Additional fee paid to rider per kilometer', max_digits=10)),
                ('service_fee_percentage', models.DecimalField(decimal_places=2, default=2.0, help_text='Platform service fee percentage added to order total', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'ordering': ['-created_at'],
            },
        ),
    ]
