# Generated by Django 5.2.4 on 2025-09-26 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_add_menu_update_tracking'),
    ]

    operations = [
    ]
