# Generated by Django 5.2 on 2025-10-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_add_conditional_payment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='featured_expiry',
            field=models.DateTimeField(blank=True, help_text='When the featured status expires', null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='featured_priority',
            field=models.IntegerField(default=0, help_text='Priority level for featured vendors (higher = more prominent)'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Whether this vendor is featured (paid promotion)'),
        ),
    ]
