# Generated by Django 5.2 on 2025-10-02 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_add_featured_vendor_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro (Featured)')], max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('description', models.TextField(blank=True, null=True)),
                ('features', models.JSONField(default=list, help_text='List of features included in this plan')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, help_text="Vendor's current subscription plan", null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.subscriptionplan'),
        ),
    ]
