# Generated by Django 5.2 on 2025-10-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_add_subscription_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierprofile',
            name='account_name',
            field=models.CharField(blank=True, help_text='Bank account name for payouts', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courierprofile',
            name='account_number',
            field=models.CharField(blank=True, help_text='Bank account number for payouts', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='courierprofile',
            name='bank_account_verified',
            field=models.BooleanField(default=False, help_text='Whether bank account has been verified'),
        ),
        migrations.AddField(
            model_name='courierprofile',
            name='bank_account_verified_at',
            field=models.DateTimeField(blank=True, help_text='When bank account was verified', null=True),
        ),
        migrations.AddField(
            model_name='courierprofile',
            name='bank_code',
            field=models.CharField(blank=True, help_text='Bank code for payouts', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='courierprofile',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank name for payouts', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courierprofile',
            name='email_verification_token',
            field=models.CharField(blank=True, help_text='Email verification token', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courierprofile',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Whether email has been verified'),
        ),
        migrations.AddField(
            model_name='courierprofile',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, help_text='When email was verified', null=True),
        ),
        migrations.AddField(
            model_name='courierprofile',
            name='phone_verification_attempts',
            field=models.IntegerField(default=0, help_text='Number of phone verification attempts'),
        ),
        migrations.AddField(
            model_name='courierprofile',
            name='phone_verification_code',
            field=models.CharField(blank=True, help_text='Phone verification code', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='courierprofile',
            name='phone_verified',
            field=models.BooleanField(default=False, help_text='Whether WhatsApp phone has been verified'),
        ),
        migrations.AddField(
            model_name='courierprofile',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, help_text='When phone was verified', null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='account_name',
            field=models.CharField(blank=True, help_text='Bank account name for payouts', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='account_number',
            field=models.CharField(blank=True, help_text='Bank account number for payouts', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='bank_account_verified',
            field=models.BooleanField(default=False, help_text='Whether bank account has been verified'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='bank_account_verified_at',
            field=models.DateTimeField(blank=True, help_text='When bank account was verified', null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='bank_code',
            field=models.CharField(blank=True, help_text='Bank code for payouts', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank name for payouts', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='email_verification_token',
            field=models.CharField(blank=True, help_text='Email verification token', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Whether email has been verified'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, help_text='When email was verified', null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='phone_verification_attempts',
            field=models.IntegerField(default=0, help_text='Number of phone verification attempts'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='phone_verification_code',
            field=models.CharField(blank=True, help_text='Phone verification code', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='phone_verified',
            field=models.BooleanField(default=False, help_text='Whether WhatsApp phone has been verified'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, help_text='When phone was verified', null=True),
        ),
    ]
