# Generated by Django 5.2 on 2025-10-13 15:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_add_bank_verification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated delivery fee based on distance', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_latitude',
            field=models.FloatField(blank=True, help_text='Delivery location latitude', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_longitude',
            field=models.FloatField(blank=True, help_text='Delivery location longitude', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_latitude',
            field=models.FloatField(blank=True, help_text='Pickup location latitude', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_longitude',
            field=models.FloatField(blank=True, help_text='Pickup location longitude', null=True),
        ),
    ]
