# Generated by Django 5.2 on 2025-10-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_order_delivery_fee_order_delivery_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, help_text='Unique referral code for user', max_length=8, null=True, unique=True),
        ),
    ]
