# Generated by Django 5.2 on 2025-10-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_user_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='video',
            field=models.FileField(blank=True, help_text='30-second promotional video for the menu item', null=True, upload_to='menu_videos/'),
        ),
    ]
