# Generated by Django 5.2 on 2025-10-19 07:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_menuitem_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='user.cart')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_food_types', models.JSONField(blank=True, default=list, null=True)),
                ('allergies', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorPopularity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('recent_order_count', models.PositiveIntegerField(default=0)),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('popularity_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='popularity', to='user.vendorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CryptoPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nowpayments_payment_id', models.CharField(max_length=100, unique=True)),
                ('payment_status', models.CharField(choices=[('waiting', 'Waiting for Payment'), ('confirming', 'Confirming Transaction'), ('confirmed', 'Transaction Confirmed'), ('sending', 'Sending to Wallet'), ('finished', 'Payment Completed'), ('failed', 'Payment Failed'), ('expired', 'Payment Expired'), ('partially_paid', 'Partially Paid'), ('refunded', 'Payment Refunded')], default='waiting', max_length=20)),
                ('pay_address', models.CharField(help_text='Crypto wallet address for payment', max_length=255)),
                ('payin_extra_id', models.CharField(blank=True, help_text='Extra ID for coins that require it', max_length=255, null=True)),
                ('pay_amount', models.DecimalField(decimal_places=8, help_text='Amount to be paid in crypto', max_digits=20)),
                ('pay_currency', models.CharField(help_text='Cryptocurrency code (btc, eth, etc.)', max_length=10)),
                ('original_amount_ngn', models.DecimalField(decimal_places=2, help_text='Original amount in Naira', max_digits=10)),
                ('exchange_rate', models.DecimalField(decimal_places=8, help_text='Exchange rate at time of payment', max_digits=15)),
                ('outcome_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('outcome_currency', models.CharField(default='ngn', max_length=10)),
                ('webhook_verified', models.BooleanField(default=False)),
                ('webhook_received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('purchase_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ipn_callback_url', models.URLField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_payments', to='user.order')),
            ],
            options={
                'db_table': 'crypto_payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['nowpayments_payment_id'], name='crypto_paym_nowpaym_2755d0_idx'), models.Index(fields=['payment_status'], name='crypto_paym_payment_aabaa2_idx'), models.Index(fields=['order', 'payment_status'], name='crypto_paym_order_i_0fd49c_idx')],
            },
        ),
        migrations.CreateModel(
            name='VendorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_ratings', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='user.vendorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('vendor', 'user')},
            },
        ),
    ]
