# Generated by Django 5.2 on 2025-10-19 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_cart_orderitem_userpreference_vendorpopularity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuUpdateReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_sent_at', models.DateTimeField(auto_now_add=True)),
                ('reminder_type', models.CharField(default='whatsapp', help_text='Channel: whatsapp/email/etc.', max_length=30)),
                ('status', models.CharField(default='pending', help_text='sent, delivered, failed', max_length=30)),
                ('message_body', models.TextField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_update_reminders', to='user.vendorprofile')),
            ],
        ),
    ]
