# Generated by Django 5.2 on 2025-10-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_menuupdatereminderlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='last_menu_update',
            field=models.DateTimeField(blank=True, help_text='When the vendor last updated their menu items', null=True),
        ),
    ]
