# Generated by Django 5.2 on 2025-10-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_cart_vendor_cart_is_active_cart_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='special_instructions',
            field=models.TextField(blank=True, help_text='Special instructions from the user', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('awaiting', 'Awaiting'), ('pending', 'Pending'), ('payment_confirmed', 'Payment Confirmed'), ('processing', 'Processing'), ('ready', 'Ready'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='awaiting', max_length=20),
        ),
    ]
