# Generated by Django 5.2 on 2025-10-24 18:12

import bestyy.core_features.user.models
import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_add_special_instructions_to_order'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_social_signup',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_complete',
        ),
        migrations.RemoveField(
            model_name='user',
            name='social_provider',
        ),
        migrations.RemoveField(
            model_name='user',
            name='social_uid',
        ),
        migrations.CreateModel(
            name='SubAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paystack_subaccount_code', models.CharField(max_length=50, unique=True)),
                ('business_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=100)),
                ('bank_code', models.CharField(max_length=10)),
                ('bank_name', models.CharField(max_length=100)),
                ('percentage_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_provider', models.CharField(blank=True, choices=[('google', 'Google'), ('facebook', 'Facebook'), ('email', 'Email')], max_length=20, null=True)),
                ('social_uid', models.CharField(blank=True, help_text="User's ID from the social provider", max_length=255, null=True)),
                ('is_social_signup', models.BooleanField(default=False, help_text='True if user signed up via social auth')),
                ('profile_complete', models.BooleanField(default=False, help_text='True if user has completed their profile')),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subaccount', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SubAccount',
                'verbose_name_plural': 'SubAccounts',
            },
            managers=[
                ('objects', bestyy.core_features.user.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Setting key (e.g., 'delivery_rate_per_km')", max_length=100, unique=True)),
                ('value', models.CharField(help_text='Setting value', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of what this setting controls', null=True)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'ordering': ['key'],
            },
        ),
    ]
