# Generated by Django 5.2.4 on 2025-11-20 13:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_image_product_video'),
        ('user', '0026_add_vendor_coordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_token', models.CharField(db_index=True, help_text='Unique JWT token for anonymous cart identification', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(help_text='Auto-expire old carts after 30 days')),
            ],
            options={
                'verbose_name': 'Anonymous Cart',
                'verbose_name_plural': 'Anonymous Carts',
                'db_table': 'anonymous_carts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='last_location_update',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='longitude',
        ),
        migrations.CreateModel(
            name='WebsiteCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of product in cart', validators=[django.core.validators.MinValueValidator(1)])),
                ('price_snapshot', models.DecimalField(decimal_places=2, help_text='Price at time of adding to cart', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anonymous_cart', models.ForeignKey(blank=True, help_text='Cart for anonymous users', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='user.anonymouscart')),
                ('product', models.ForeignKey(help_text='Product being added to cart', on_delete=django.db.models.deletion.CASCADE, related_name='website_cart_items', to='product.product')),
                ('user', models.ForeignKey(blank=True, help_text='User for authenticated cart', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='website_cart_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Website Cart Item',
                'verbose_name_plural': 'Website Cart Items',
                'db_table': 'website_cart_items',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('anonymous_cart__isnull', False)), fields=('anonymous_cart', 'product'), name='unique_anonymous_cart_product'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'product'), name='unique_user_product')],
            },
        ),
    ]
