# Generated by Django 5.2 on 2025-10-25 07:17

import bestyy.core_features.user.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_alter_user_managers_remove_user_is_social_signup_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailystats',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dailystats',
            name='courier',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subaccount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='subscription_plan',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='vendoranalytics',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='vendoranalytics',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='vendorpopularity',
            name='vendor',
        ),
        migrations.AlterUniqueTogether(
            name='vendorrating',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='vendorrating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vendorrating',
            name='vendor',
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', bestyy.core_features.user.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='TransferRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('vendor', 'Vendor'), ('courier', 'Courier')], max_length=20)),
                ('paystack_recipient_code', models.CharField(max_length=50, unique=True)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=100)),
                ('bank_code', models.CharField(max_length=10)),
                ('bank_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_recipient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transfer Recipient',
                'verbose_name_plural': 'Transfer Recipients',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paystack_reference', models.CharField(max_length=100, unique=True)),
                ('paystack_transfer_code', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='user.order')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='user.transferrecipient')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.DeleteModel(
            name='CryptoPayment',
        ),
        migrations.DeleteModel(
            name='DailyStats',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='SubAccount',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
        migrations.DeleteModel(
            name='VendorAnalytics',
        ),
        migrations.DeleteModel(
            name='VendorPopularity',
        ),
        migrations.DeleteModel(
            name='VendorRating',
        ),
    ]
