# Generated by Django 5.2.4 on 2025-11-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_multi_role_authentication'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='courierprofile',
            name='bank_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='courierprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courierprofile',
            name='paystack_recipient_code',
            field=models.CharField(blank=True, help_text='Paystack transfer recipient code for automated payments', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='bank_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='paystack_recipient_code',
            field=models.CharField(blank=True, help_text='Paystack transfer recipient code for automated payments', max_length=100, null=True),
        ),
    ]
