# Generated by Django 5.2 on 2025-10-25 07:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_add_transfer_models'),
    ]

    operations = [
        # Recreate deleted models
        migrations.CreateModel(
            name='SubAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paystack_subaccount_code', models.CharField(max_length=50, unique=True)),
                ('business_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=100)),
                ('bank_code', models.CharField(max_length=10)),
                ('bank_name', models.CharField(max_length=100)),
                ('fixed_payout_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, help_text="If you want to store a fixed payout for audits, not used in transactions anymore.")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subaccount', to='user.user')),
            ],
            options={
                'verbose_name': 'SubAccount',
                'verbose_name_plural': 'SubAccounts',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('payment_method', models.CharField(choices=[('card', 'Bank Card'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('paystack_reference', models.CharField(max_length=100, unique=True)),
                ('paystack_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_deliveries', models.IntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_delivery_time', models.FloatField(default=0, help_text='Average delivery time in minutes')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='user.courierprofile')),
            ],
            options={
                'unique_together': {('courier', 'date')},
                'ordering': ['-date'],
                'verbose_name': 'Daily Stats',
                'verbose_name_plural': 'Daily Stats',
            },
        ),
        migrations.CreateModel(
            name='VendorAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_of_week', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('avg_order_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='user.vendorprofile')),
            ],
            options={
                'unique_together': {('vendor', 'date')},
                'ordering': ['-date', 'day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='VendorPopularity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('recent_order_count', models.PositiveIntegerField(default=0)),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('popularity_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='popularity', to='user.vendorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='VendorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_ratings', to='user.user')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='user.vendorprofile')),
            ],
            options={
                'unique_together': {('vendor', 'user')},
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_food_types', models.JSONField(blank=True, default=list, null=True)),
                ('allergies', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='CryptoPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('nowpayments_payment_id', models.CharField(max_length=100, unique=True)),
                ('payment_status', models.CharField(choices=[('waiting', 'Waiting for Payment'), ('confirming', 'Confirming Transaction'), ('confirmed', 'Transaction Confirmed'), ('sending', 'Sending to Wallet'), ('finished', 'Payment Completed'), ('failed', 'Payment Failed'), ('expired', 'Payment Expired'), ('partially_paid', 'Partially Paid'), ('refunded', 'Payment Refunded')], default='waiting', max_length=20)),
                ('pay_address', models.CharField(help_text='Crypto wallet address for payment', max_length=255)),
                ('payin_extra_id', models.CharField(blank=True, help_text='Extra ID for coins that require it', max_length=255, null=True)),
                ('pay_amount', models.DecimalField(decimal_places=8, help_text='Amount to be paid in crypto', max_digits=20)),
                ('pay_currency', models.CharField(help_text='Cryptocurrency code (btc, eth, etc.)', max_length=10)),
                ('original_amount_ngn', models.DecimalField(decimal_places=2, help_text='Original amount in Naira', max_digits=10)),
                ('exchange_rate', models.DecimalField(decimal_places=8, help_text='Exchange rate at time of payment', max_digits=15)),
                ('outcome_amount', models.DecimalField(blank=True, decimal_places=8, help_text='Amount received after conversion', max_digits=20, null=True)),
                ('outcome_currency', models.CharField(default='ngn', max_length=10)),
                ('webhook_verified', models.BooleanField(default=False)),
                ('webhook_received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('purchase_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ipn_callback_url', models.URLField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_payments', to='user.order')),
            ],
            options={
                'db_table': 'crypto_payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['nowpayments_payment_id'], name='crypto_pay_id_idx'), models.Index(fields=['payment_status'], name='crypto_pay_status_idx'), models.Index(fields=['order', 'payment_status'], name='crypto_order_status_idx')],
            },
        ),
        # Restore fields that were removed from existing models
        migrations.AddField(
            model_name='order',
            name='delivery_otp',
            field=models.CharField(blank=True, max_length=6, null=True, help_text='OTP for delivery confirmation'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_otp_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_otp_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro (Featured)')], max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('description', models.TextField(blank=True, null=True)),
                ('features', models.JSONField(default=list, help_text='List of features included in this plan')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
