# Generated by Django 5.2 on 2025-11-21 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_courierprofile_bank_account_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Banner title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Banner description', null=True)),
                ('banner_image', models.ImageField(help_text='Recommended size: 1180x192 pixels', upload_to='banners/')),
                ('banner_type', models.CharField(choices=[('homepage', 'Homepage Banner'), ('promotional', 'Promotional Banner'), ('seasonal', 'Seasonal Banner'), ('vendor_spotlight', 'Vendor Spotlight')], default='homepage', help_text='Type of banner', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('scheduled', 'Scheduled'), ('expired', 'Expired')], default='active', help_text='Banner status', max_length=20)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority banners appear first')),
                ('click_url', models.URLField(blank=True, help_text='URL to redirect when banner is clicked', null=True)),
                ('display_start_date', models.DateTimeField(blank=True, help_text='When to start displaying the banner', null=True)),
                ('display_end_date', models.DateTimeField(blank=True, help_text='When to stop displaying the banner', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether banner is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created the banner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_banners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
