# Generated by Django 5.2 on 2025-10-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_restore_deleted_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=16)),
                ('user_type', models.CharField(choices=[('vendor', 'Vendor'), ('courier', 'Courier')], max_length=10)),
                ('verification_code', models.CharField(max_length=6)),
                ('code_generated_at', models.DateTimeField(auto_now_add=True)),
                ('profile_data', models.JSONField(default=dict)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='cryptopayment',
            name='order',
        ),
        migrations.AlterUniqueTogether(
            name='dailystats',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dailystats',
            name='courier',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subaccount',
            name='user',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='vendoranalytics',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='vendoranalytics',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='vendorpopularity',
            name='vendor',
        ),
        migrations.AlterUniqueTogether(
            name='vendorrating',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='vendorrating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vendorrating',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_otp',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_otp_generated_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_otp_verified',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_otp_verified_at',
        ),
        migrations.AddIndex(
            model_name='pendinguser',
            index=models.Index(fields=['email'], name='user_pendin_email_d37cd0_idx'),
        ),
        migrations.AddIndex(
            model_name='pendinguser',
            index=models.Index(fields=['phone'], name='user_pendin_phone_cdb35d_idx'),
        ),
        migrations.AddIndex(
            model_name='pendinguser',
            index=models.Index(fields=['verification_code'], name='user_pendin_verific_2c393d_idx'),
        ),
        migrations.AddIndex(
            model_name='pendinguser',
            index=models.Index(fields=['expires_at'], name='user_pendin_expires_6e3d32_idx'),
        ),
        migrations.DeleteModel(
            name='CryptoPayment',
        ),
        migrations.DeleteModel(
            name='DailyStats',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='SubAccount',
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
        migrations.DeleteModel(
            name='VendorAnalytics',
        ),
        migrations.DeleteModel(
            name='VendorPopularity',
        ),
        migrations.DeleteModel(
            name='VendorRating',
        ),
    ]
