# Generated by Django 5.2 on 2025-12-01 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_banner'),
        ('whatsapp_ai', '0009_whatsappconversation_context_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone', models.CharField(help_text='Customer WhatsApp phone number', max_length=20)),
                ('customer_name', models.CharField(blank=True, help_text='Customer name if available', max_length=100, null=True)),
                ('trigger_type', models.CharField(choices=[('complaint_general', 'General Complaint'), ('complaint_service', 'Service Quality Complaint'), ('complaint_food', 'Food Quality Complaint'), ('complaint_delivery', 'Delivery Issue'), ('complaint_payment', 'Payment Issue'), ('insult_severe', 'Severe Language Violation'), ('insult_multiple', 'Multiple Inappropriate Language'), ('system_error', 'System Technical Error'), ('user_request', 'User Requested Human Assistance'), ('other', 'Other Issue')], default='complaint_general', max_length=30)),
                ('description', models.TextField(help_text='Description of the complaint/issue')),
                ('severity_level', models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('resolution_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('contact_scheduled', 'Contact Scheduled'), ('contacted', 'Customer Contacted'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes about the resolution process', null=True)),
                ('contact_attempts', models.PositiveIntegerField(default=0, help_text='Number of times customer contact was attempted')),
                ('last_contact_attempt', models.DateTimeField(blank=True, help_text='Last time contact was attempted', null=True)),
                ('contact_successful', models.BooleanField(default=False, help_text='Whether customer was successfully contacted')),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Additional context data about the escalation')),
                ('escalation_reason', models.CharField(help_text='Reason for escalation', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_agent', models.ForeignKey(blank=True, help_text='Support agent assigned to handle this escalation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_escalations', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='whatsapp_ai.whatsappconversation')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_escalations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support Escalation',
                'verbose_name_plural': 'Support Escalations',
                'ordering': ['-created_at'],
            },
        ),
    ]
