# Generated by Django 5.2.4 on 2025-07-16 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=16)),
                ('service_areas', models.CharField(max_length=255)),
                ('delivery_radius', models.CharField(max_length=50)),
                ('opening_hours', models.TimeField()),
                ('closing_hours', models.TimeField()),
                ('has_bike', models.BooleanField(default=False)),
                ('verification_preference', models.CharField(choices=[('NIN', 'NIN'), ('DL', "Driver's License"), ('VC', "Voter's Card")], max_length=50)),
                ('nin_number', models.CharField(blank=True, max_length=20, null=True)),
                ('id_upload', models.ImageField(blank=True, null=True, upload_to='courier_ids/')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='courier_photos/')),
                ('agreed_to_terms', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=16)),
                ('business_name', models.CharField(max_length=255)),
                ('business_category', models.CharField(max_length=100)),
                ('cac_number', models.CharField(blank=True, max_length=100, null=True)),
                ('business_description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='vendor_logos/')),
                ('business_address', models.CharField(max_length=255)),
                ('delivery_radius', models.CharField(max_length=50)),
                ('service_areas', models.CharField(max_length=255)),
                ('opening_hours', models.TimeField()),
                ('closing_hours', models.TimeField()),
                ('offers_delivery', models.BooleanField(default=False)),
                ('plan', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_items/')),
                ('available_now', models.BooleanField(default=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='user.vendorprofile')),
            ],
        ),
    ]
