# Generated by Django 5.2.4 on 2025-08-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Regular User'), ('vendor', 'Vendor'), ('courier', 'Courier')], default='user', max_length=10),
        ),
    ]
