# Generated by Django 5.2.4 on 2025-07-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_order_delivery_address_order_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierprofile',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('bike', 'Bike'), ('car', 'Car'), ('van', 'Van'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
